# Generated by Django 5.0.1 on 2024-02-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0002_category_modelcourse_modelsession_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="testingJson",
            field=models.JSONField(default="False"),
            preserve_default=False,
        ),
    ]
