# Generated by Django 5.0.1 on 2024-02-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0003_question_testingjson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="testingJson",
        ),
        migrations.AlterField(
            model_name="question",
            name="incorrect_answers",
            field=models.JSONField(),
        ),
    ]
