# Generated by Django 5.0.1 on 2024-02-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0005_section_modelsession_afterclass_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcourse",
            name="description",
            field=models.TextField(default="_"),
        ),
        migrations.AddField(
            model_name="modelcourse",
            name="textBook",
            field=models.CharField(default="_", max_length=100),
        ),
    ]
