# Generated by Django 5.0.1 on 2024-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0006_modelcourse_description_modelcourse_textbook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelsession",
            name="questions",
        ),
        migrations.AddField(
            model_name="section",
            name="questions",
            field=models.ManyToManyField(to="language.question"),
        ),
        migrations.AlterField(
            model_name="modelsession",
            name="afterClass",
            field=models.ManyToManyField(
                related_name="after_class_section", to="language.section"
            ),
        ),
        migrations.AlterField(
            model_name="modelsession",
            name="beforeClass",
            field=models.ManyToManyField(
                related_name="before_class_section", to="language.section"
            ),
        ),
        migrations.AlterField(
            model_name="modelsession",
            name="inClass",
            field=models.ManyToManyField(
                related_name="in_class_section", to="language.section"
            ),
        ),
    ]
