# Generated by Django 5.0.1 on 2024-02-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0007_remove_modelsession_questions_section_questions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="questionsJSON",
            field=models.JSONField(default={"questions": {}}),
        ),
    ]
