# Generated by Django 5.0.1 on 2024-02-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0008_section_questionsjson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="questionsJSON",
            field=models.JSONField(default={"questions": []}),
        ),
    ]
