# Generated by Django 5.0.1 on 2024-02-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0009_alter_section_questionsjson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelsession",
            name="afterClass",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="after_class_section",
                to="language.section",
            ),
        ),
        migrations.AlterField(
            model_name="modelsession",
            name="beforeClass",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="before_class_section",
                to="language.section",
            ),
        ),
        migrations.AlterField(
            model_name="modelsession",
            name="inClass",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="in_class_section",
                to="language.section",
            ),
        ),
    ]
