# Generated by Django 5.0.1 on 2024-02-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0010_alter_modelsession_afterclass_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcourse",
            name="color",
            field=models.CharField(default="white", max_length=40),
        ),
        migrations.AddField(
            model_name="modelcourse",
            name="progress",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="modelcourse",
            name="description",
            field=models.TextField(default="Follow these simple steps"),
        ),
        migrations.AlterField(
            model_name="modelcourse",
            name="textBook",
            field=models.CharField(default="Streamline Departure", max_length=100),
        ),
    ]
