# Generated by Django 5.0.1 on 2024-02-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0011_modelcourse_color_modelcourse_progress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcourse",
            name="bgCardUrlSecondary",
            field=models.CharField(default="_", max_length=200),
        ),
        migrations.AddField(
            model_name="modelcourse",
            name="category",
            field=models.ManyToManyField(
                related_name="course_category", to="language.category"
            ),
        ),
        migrations.AddField(
            model_name="modelcourse",
            name="sale",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="modelcourse",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
