# Generated by Django 5.0.1 on 2024-02-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "language",
            "0012_modelcourse_bgcardurlsecondary_modelcourse_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="modelsession",
            name="bgCardUrl",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="modelsession",
            name="color",
            field=models.CharField(
                blank=True, default="white", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="modelsession",
            name="level",
            field=models.CharField(
                blank=True, default="Beginner", max_length=70, null=True
            ),
        ),
        migrations.AddField(
            model_name="modelsession",
            name="section",
            field=models.ManyToManyField(related_name="Section", to="language.section"),
        ),
        migrations.AddField(
            model_name="modelsession",
            name="topics",
            field=models.CharField(
                blank=True, default="English", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="modelcourse",
            name="sale",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="modelsession",
            name="CPTUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="modelsession",
            name="PPTFileUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="modelsession",
            name="afterClass",
            field=models.ManyToManyField(
                blank=True, related_name="after_class_section", to="language.section"
            ),
        ),
        migrations.AlterField(
            model_name="modelsession",
            name="beforeClass",
            field=models.ManyToManyField(
                blank=True, related_name="before_class_section", to="language.section"
            ),
        ),
        migrations.AlterField(
            model_name="modelsession",
            name="inClass",
            field=models.ManyToManyField(
                blank=True, related_name="in_class_section", to="language.section"
            ),
        ),
        migrations.AlterField(
            model_name="modelsession",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
    ]
