# Generated by Django 5.0.1 on 2024-02-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0013_modelsession_bgcardurl_modelsession_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelsession",
            name="section",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="Section", to="language.section"
            ),
        ),
    ]
