# Generated by Django 5.0.1 on 2024-02-24 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0014_alter_modelsession_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelsession",
            name="afterClass",
        ),
        migrations.RemoveField(
            model_name="modelsession",
            name="beforeClass",
        ),
        migrations.RemoveField(
            model_name="modelsession",
            name="inClass",
        ),
        migrations.RemoveField(
            model_name="section",
            name="externalLink",
        ),
        migrations.RemoveField(
            model_name="section",
            name="questions",
        ),
        migrations.RemoveField(
            model_name="section",
            name="timeSpan",
        ),
    ]
