# Generated by Django 5.0.1 on 2024-02-24 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "language",
            "0016_rename_title_section_name_remove_section_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelsession",
            name="section",
        ),
        migrations.AddField(
            model_name="section",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="language.modelsession",
            ),
        ),
    ]
