# Generated by Django 5.0.1 on 2024-02-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0020_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
