# Generated by Django 5.0.1 on 2024-02-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0022_exercise_description_exercise_instruction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="school",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
    ]
