# Generated by Django 5.0.1 on 2024-02-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0023_profile_school_alter_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="exerciseLog",
            field=models.JSONField(default={}),
        ),
    ]
