# Generated by Django 5.0.1 on 2024-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0024_profile_exerciselog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("bgCardUrl", models.URLField(blank=True, null=True)),
                ("serial", models.CharField(default="", max_length=100)),
                ("description", models.TextField(default="")),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="exerciseLog",
            field=models.JSONField(default=dict),
        ),
    ]
