# Generated by Django 5.0.1 on 2024-03-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0025_resource_alter_profile_exerciselog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
