# Generated by Django 5.0.1 on 2024-03-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0028_contact_delete_contactrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="courseSave",
            field=models.CharField(default="/", max_length=300),
        ),
    ]
