# Generated by Django 5.0.1 on 2024-03-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0029_profile_coursesave"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="bannerUrl",
            field=models.URLField(
                default="https://img.freepik.com/free-psd/realistic-roll-up-mock-up_1104-171.jpg?size=626&ext=jpg&uid=R140040626&ga=GA1.1.1279301610.1706777722&semt=ais"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="blogSave",
            field=models.CharField(default="/", max_length=300),
        ),
    ]
