# Generated by Django 5.0.1 on 2024-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0030_category_bannerurl_profile_blogsave"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="bgCardUrl",
            field=models.URLField(
                default="https://img.freepik.com/free-photo/workplace-with-open-notebook_1101-349.jpg?t=st=1709636664~exp=1709640264~hmac=e0b68f45114336a69e6d5ed40f4f271a4c89bb40012373021542a842501ac5bb&w=826"
            ),
        ),
    ]
