# Generated by Django 5.0.1 on 2024-03-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0032_remove_modelcourse_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="courseAuth",
            field=models.CharField(default="/", max_length=300),
        ),
    ]
