# Generated by Django 5.0.1 on 2024-04-20 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0033_profile_courseauth"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("question", models.TextField()),
                ("description", models.CharField(default="", max_length=200)),
                ("answer", models.TextField(blank=True, null=True)),
                ("images", models.TextField(blank=True, null=True)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField()),
                ("session", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
