# Generated by Django 5.0.1 on 2024-04-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0034_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
