# Generated by Django 5.0.1 on 2024-04-23 03:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("language", "0035_alter_assignment_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="user",
            new_name="student",
        ),
    ]
